name: Reusable - Flake Check

on:
  workflow_call:
    inputs:
      has_changes:
        required: true
        type: string
      use_cachix:
        required: false
        type: boolean
        default: false

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    if: inputs.has_changes == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Setup Cachix
        if: inputs.use_cachix
        uses: cachix/cachix-action@v15
        with:
          name: kaiiiiiiiii
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check flake health
        uses: DeterminateSystems/flake-checker-action@main

      - name: Run flake check
        run: nix flake check --all-systems -L
